version: "3"
services:
  php_request_listener:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: php:latest
    working_dir: /application
    volumes:
      - .:/application
    networks:
      proxy:
        ipv4_address: 10.200.4.1

  nginx:
    image: nginx:alpine
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_request_listener
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.request_listener.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.request_listener.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.4.2

networks:
  proxy:
    external: true
